//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
//! Hand-edited to add rotation columns (family_id, status, replaced_by, rotated_at).
//! Regenerate against a live DB after running migration 20260618120000.

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "refresh_tokens"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub jti: Uuid,
    pub user_id: Uuid,
    pub revoked: bool,
    pub expires_at: Option<DateTime>,
    pub created_at: DateTime,
    /// Shared across all tokens in one rotation lineage.
    pub family_id: Uuid,
    /// Token lifecycle: "active" | "rotated" | "revoked"
    pub status: String,
    /// Id of the token that superseded this one (diagnostics only).
    pub replaced_by: Option<Uuid>,
    /// When this token was rotated (UTC, diagnostics only).
    pub rotated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Jti,
    UserId,
    Revoked,
    ExpiresAt,
    CreatedAt,
    FamilyId,
    Status,
    ReplacedBy,
    RotatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::Jti => ColumnType::Uuid.def().unique(),
            Self::UserId => ColumnType::Uuid.def(),
            Self::Revoked => ColumnType::Boolean.def(),
            Self::ExpiresAt => ColumnType::DateTime.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::FamilyId => ColumnType::Uuid.def(),
            Self::Status => ColumnType::Text.def(),
            Self::ReplacedBy => ColumnType::Uuid.def().null(),
            Self::RotatedAt => ColumnType::TimestampWithTimeZone.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
